name: Deploy to Raspberry Pi

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull Latest Code Safely
        run: |
          cd ~/Glep
          git stash
          git pull origin main
          git stash pop || true
          npm install

      - name: Restart or Start Bot with PM2
        run: |
          cd ~/Glep
          pm2 restart glep-bot || pm2 start src/index.js --name "glep-bot"
          pm2 save